# Database JDBC C3P0

db.config.url: jdbc:mysql://localhost:3306/qlipon?serverTimezone=UTC
db.config.driver_class: com.mysql.cj.jdbc.Driver

db.cred.username: hpark
db.cred.password: howdy898

db.c3p0.init_pool: 5
db.c3p0.min_pool: 5
db.c3p0.max_pool: 20
db.c3p0.acquire_increment: 5
db.c3p0.max_statements: 180


# Google Vision Api
google.api_key: 031d5ae9703b52acfa2b40275e93c7b3a088ded3
google.url: https://vision.googleapis.com/v1/images:annotate?fields=responses%2FtextAnnotations%2Fscore&key=
